version: '3.8'

services:
  # * DATABASE
  mysql_db:
    container_name: mysql_db
    image: mysql/mysql-server:8.0.29
    volumes:
      - ./db/data:/var/lib/mysql
      # - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  # * API
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/:/opt/app/config
    depends_on:
      - mysql_db
    ports:
      - 5000:5000
    command: [ --config, config/api.yaml, --host, api, --port, '5000' ]
